services:
    php:
        image: ${DOCKER_IMAGE_TAG_PREFIX}/php:${DOCKER_IMAGE_TAG}
        build:
            context: .
            dockerfile: ./config/docker/php/Dockerfile
        volumes:
            - /var/www/.composer
